trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    npm run test-ci   
    ls /coverage
    ls     
  displayName: 'npm install, unitTest and build'
  

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'azure-devopsUdem2'
    organization: 'alejom95'
    scannerMode: 'CLI'
    configMode: 'file'
    configFile: './sonar-project.properties'
    
  
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/pet-book'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/pet-book-$(Build.BuildId).zip'
    replaceExistingArchive: true
    

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: S3Upload@1
  inputs:
    awsCredentials: 'aws-devopsUdem'
    regionName: 'us-east-2'
    bucketName: 'bucketpruebapet-book'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/'
    globExpressions: '*.zip'
    targetFolder: 'artefactos'
    createBucket: true

- task: Docker@2
  inputs:
    containerRegistry: 'docker_hub'
    repository: 'pet-book-udem'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: 'alejandrom24/imagenprueba:$(Build.BuildId)'

    


